enable_collision_marker: True
enable_visualization: True
plot_trajectory: True
debug: False
map_frame: map 
joint_convergence_threshold: 0.001
wiggle_precision_threshold: 5
max_traj_length: 30 # not implemented
sample_period: 0.1
default_joint_vel_limit: 0.25
default_joint_weight: 0.001
joint_weights:
  odom_x_joint: 1
  odom_y_joint: 1
  odom_z_joint: 1
  refills_finger: 0.1
collision_avoidance:
  default:
    max_weight_distance: 0.0
    low_weight_distance: 0.01
    zero_weight_distance: 0.05
  high: &high
    max_weight_distance: 0.01
    low_weight_distance: 0.03
    zero_weight_distance: 0.05
  base_link:
    max_weight_distance: 0.04
    low_weight_distance: 0.06
    zero_weight_distance: 0.09
  l_upper_arm_link: *high
  r_upper_arm_link: *high
  l_forearm_link: *high
  r_forearm_link: *high
fill_velocity_values: True
nWSR: None # None results in a nWSR estimation thats fine most of the time
root_link: odom
collision_time_threshold: 15
tree_tick_rate: 0.1
slerp: True