parent: !include default.yaml
collision_avoidance:
  external_collision_avoidance:
    distance_thresholds: # external thresholds are per joint, they therefore count for all directly controlled links
      default:
        hard_threshold: 0.0 # at this distance in [cm] that can not be surpassed
        soft_threshold: 0.05 # robot links are pushed to that distance, but it can be overpowered with high weight constraints
      override:
        odom_z_joint: # this affects all links between this and the next controlled joint
          hard_threshold: 0.02 # at this distance in [cm] that can not be surpassed
          soft_threshold: 0.7 # robot links are pushed to that distance, but it can be overpowered with high weight constraints
    # each controlled joint gets pushed away from its X nearest objects
    # to reduce the runtime, you can set different values for joints that control end effectors
    number_of_repeller:
      default: 1
      end_effector_joints: 4

