parent: !include pr2.yaml
action_server:
  /pr2_a/base:
    plugin: SendFollowJointTrajectory
    namespace: /pr2_a/whole_body_controller/base/follow_joint_trajectory
    state_topic: /pr2_a/whole_body_controller/base/state
    fill_velocity_values: True
  /pr2_a/body:
    plugin: SendFollowJointTrajectory
    namespace: /pr2_a/whole_body_controller/body/follow_joint_trajectory
    state_topic: /pr2_a/whole_body_controller/body/state
    fill_velocity_values: False
  /pr2_b/base:
    plugin: SendFollowJointTrajectory
    namespace: /pr2_b/whole_body_controller/base/follow_joint_trajectory
    state_topic: /pr2_b/whole_body_controller/base/state
    fill_velocity_values: True
  /pr2_b/body:
    plugin: SendFollowJointTrajectory
    namespace: /pr2_b/whole_body_controller/body/follow_joint_trajectory
    state_topic: /pr2_b/whole_body_controller/body/state
    fill_velocity_values: False