name: CI standalone
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - devel
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build_dependencies:
    uses: ./.github/workflows/build_dependencies.yml
  hsr:
    needs: [ build_dependencies ]
#    strategy:
#      matrix:
#        test: [ TestJointGoals,
#                TestCollisionAvoidanceGoals,
#                TestConstraints ]
    uses: ./.github/workflows/reusable_robot_ci.yml
    with:
      robot: hsr
      test1: test/test_integration_hsr.py::TestJointGoals
      test2: test/test_integration_hsr.py::TestCollisionAvoidanceGoals
      test3: test/test_integration_hsr.py::TestConstraints
#  donbot:
#    needs: [ build_dependencies ]
#    strategy:
#      matrix:
#        test: [ TestCartGoals,
#                TestConstraints,
#                TestJointGoals ]
#    uses: ./.github/workflows/reusable_robot_ci.yml
#    with:
#      robot: donbot
#      test: test/test_integration_donbot.py::${{ matrix.test }}
#  pr2:
#    needs: [ build_dependencies ]
#    strategy:
#      matrix:
#        test: [ TestWorldManipulation,
#                TestJointGoals,
#                TestCartGoals,
#                TestConstraints,
#                TestWayPoints,
#                TestInfoServices,
#                TestSelfCollisionAvoidance,
#                TestCollisionAvoidanceGoals ]
#    uses: ./.github/workflows/reusable_robot_ci.yml
#    with:
#      robot: pr2
#      test: test/test_integration_pr2.py::${{ matrix.test }}
#  tiago:
#    needs: [ build_dependencies ]
#    strategy:
#      matrix:
#        test: [ TestConstraints,
#                TestJointGoals,
#                TestCollisionAvoidance,
#                TestCartGoals ]
#    uses: ./.github/workflows/reusable_robot_ci.yml
#    with:
#      robot: tiago
#      test: test/test_integration_tiago_stand_alone.py::${{ matrix.test }}
