name: CI
on:
#   push:
#     branches: [ devel ]
#   pull_request:
#     branches: [ devel ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'ros_ws/src/giskardpy' 
        repository: ichumuh/giskardpy
        ref: devel
    - name: Checkout giskard msgs
      uses: actions/checkout@v2
      with:
        path: 'ros_ws/src/giskard_msgs'
        repository: SemRoCo/giskard_msgs
    - name: Checkout qpoases
      uses: actions/checkout@v2
      with:
        path: 'ros_ws/src/qpOASES'
        repository: SemRoCo/qpOASES
        ref: noetic
    - name: Checkout iai_pr2
      uses: actions/checkout@v2
      with:
        path: 'ros_ws/src/iai_pr2'
        repository: code-iai/iai_pr2
        ref: mujoco_sim_setup
    - name: Checkout iai_maps
      uses: actions/checkout@v2
      with:
        path: 'ros_ws/src/iai_maps'
        repository: code-iai/iai_maps
        ref: master
    - name: Setup Giskard workspace
      uses: betwo/github-setup-catkin@master
      env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        # Version range or exact version of ROS version to use, using SemVer's version range syntax. 
        ros-version: noetic
        build-tool: 'catkin_tools'
        # Root directory of the catkin workspace
        workspace: $GITHUB_WORKSPACE/ros_ws
    - name: install python deps
      shell: bash
      run: |
        sudo pip3 install numpy==1.23.4 pandas
        python -m pytest --version
#    - name: install Giskard deps
#      shell: bash
#      run: |
#        sudo apt install python3-dev ros-noetic-pr2-description
    - name: build Giskard
      shell: bash
      run: |
        cd ros_ws
        touch src/iai_pr2/iai_pr2_sim/CATKIN_IGNORE
        touch src/iai_pr2/iai_pr2_donbot/CATKIN_IGNORE
        catkin build
#    - name: build betterpybullet
#      shell: bash
#      run: |
#        mkdir betterpybullet
#        source $GITHUB_WORKSPACE/ros_ws/devel/setup.bash
#        roscd giskardpy
#        ./scripts/build_better_pybullet.sh /betterpybullet
#  pr2-TestConstraints:
    - name: Run Giskard
      shell: bash
      run: |
        export ROS_HOSTNAME=localhost
        . ~/.bashrc
        . $GITHUB_WORKSPACE/ros_ws/devel/setup.bash
        roscore &
        roscd giskardpy
        python3 -m pytest -s test/test_integration_pr2.py::TestConstraints::test_pointing
#    - name: Setup upterm session
##      if: always()
#      if: failure()
#      uses: lhotari/action-upterm@v1
  job2:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - name: Setup upterm session
      if: always()
      uses: lhotari/action-upterm@v1
