name: CI HSR standalone
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  push:
    branches:
      - master
#      - devel
  pull_request:
    branches:
      - master
      - devel
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  hsr_standalone_tests:
    strategy:
      matrix:
        test: [TestJointGoals,
               TestCollisionAvoidanceGoals,
               TestConstraints]
    uses: SemRoCo/giskardpy/.github/workflows/reusable_robot_ci.yml@new_solvers
    with:
      robot: hsr
      test: test/test_integration_hsr.py::${{ matrix.test }}
#    - name: Setup upterm session
##      if: always()
#      if: failure()
#      uses: lhotari/action-upterm@v1
