name: CI HSR standalone
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  push:
    branches:
      - master
#      - devel
  pull_request:
    branches:
      - master
      - devel
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  hsr_joint_goals:
    uses: SemRoCo/giskardpy/.github/workflows/reusable_robot_ci.yml@new_solvers
    with:
      robot: hsr
      test: test/test_integration_hsr.py::TestJointGoals
#    - name: HSR TestCartGoals
#      run: |
#        roscd giskardpy
#        python3 -m pytest -s test/test_integration_hsr.py::TestCartGoals
#    - name: HSR TestCollisionAvoidanceGoals
#      run: |
#        roscd giskardpy
#        python3 -m pytest -s test/test_integration_hsr.py::TestCollisionAvoidanceGoals
#    - name: HSR TestConstraints
#      run: |
#        roscd giskardpy
#        python3 -m pytest -s test/test_integration_hsr.py::TestConstraints
#    - name: Setup upterm session
##      if: always()
#      if: failure()
#      uses: lhotari/action-upterm@v1
