name: CI
on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'ros_ws/src/giskardpy' 
    - name: Checkout giskard msgs
      uses: actions/checkout@v2
      with:
        path: 'ros_ws/src/giskard_msgs'
        repository: https://github.com/SemRoCo/giskard_msgs
    - name: Checkout qpoases
      uses: actions/checkout@v2
      with:
        path: 'ros_ws/src/qpOASES'
        repository: https://github.com/SemRoCo/qpOASES/tree/noetic
    - name: Setup Giskard workspace
      uses: betwo/github-setup-catkin@master
      env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        # Version range or exact version of ROS version to use, using SemVer's version range syntax. 
        ros-version: noetic
        # Root directory of the catkin workspace
        workspace: $GITHUB_WORKSPACE/ros_ws
    - name: Build KnowRob workspace
      shell: bash
      run: |
        sudo pip3 install scipy casadi sortedcontainers hypothesis pandas numpy trimesh colour pycollada catkin-tools
        sudo apt install python3-dev 
        cd ros_ws
        catkin build
    - name: Run Giskard
      shell: bash
      run: |
        export ROS_HOSTNAME=localhost
        roscore &
        source $GITHUB_WORKSPACE/ros_ws/devel/setup.bash
        roslaunch giskardpy giskardpy_pr2_standalone.launch
#     - name: Report plunit results as Github Actions Annotations
#       uses: daniel86/junit-report-annotations-action@master
#       with:
#         path: junit-*.xml
#         stripFromPath: /home/runner/work/knowrob/knowrob/ros_ws/src/knowrob/
#         accessToken: ${{ secrets.GITHUB_TOKEN }}
    #####
#     - name: Run pldoc
#       if: ${{ github.event_name == 'push' }}
#       shell: bash
#       run: |
#         source $GITHUB_WORKSPACE/ros_ws/devel_isolated/setup.bash
#         cp $GITHUB_WORKSPACE/ros_ws/src/knowrob/README.md $GITHUB_WORKSPACE/ros_ws/src/knowrob/src/
#         rosrun rosprolog rosprolog-doc knowrob
#     - name: Move checkout
#       run: |
#         mv $GITHUB_WORKSPACE/ros_ws/src/knowrob/.git $GITHUB_WORKSPACE/
#         mv $GITHUB_WORKSPACE/ros_ws/src/knowrob/* $GITHUB_WORKSPACE/
#     - name: Extract branch name
#       shell: bash
#       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
#       id: extract_branch
#     - name: Deploy pldoc to gh-pages
#       if: ${{ github.event_name == 'push' }}
#       uses: JamesIves/github-pages-deploy-action@3.5.7
#       with:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         # The branch the action should deploy to.
#         BRANCH: gh-pages
#         # The folder the action should deploy.
#         FOLDER: doc
#         # The folder in the target branch
#         TARGET_FOLDER: ${{ steps.extract_branch.outputs.branch }}
#         CLEAN: true
#         SINGLE_COMMIT: true
